name: Deploy

on:
  push:
    branches: 
    - main 

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
        - 12
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::615303692389:role/github-actions-role
        aws-region: ap-south-1
    - name: npm install
      env:
        CI: true
      run: |
        npm ci
    - name: deploy
      run: |
        npx ncc build index.ts
        zip -j deploy.zip ./dist/*
        aws lambda update-function-code --function-name=lambda-github-action-example --zip-file=fileb://deploy.zip

